# Generated by Django 6.0.1 on 2026-01-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comic",
            name="index",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
