# Generated by Django 6.0.1 on 2026-01-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comics", "0002_comic_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="comic",
            name="img_src",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
