# Generated by Django 6.0.1 on 2026-02-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comics", "0003_comic_img_src"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comic",
            name="alt_text",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
